- javascript-modules-engine-java/pom.xml
https://jira.jahia.org/browse/SEC-122
Bump the version of _java-ts-bind-all_ to include the security fixes of https://github.com/Jahia/java-ts-bind/pull/2.
> SEC-122: Bump java-ts-bind version to fix vulnerabilities

- javascript-modules-engine-java/src/main/java/org/jahia/modules/javascript/modules/engine/jsengine/GraalVMEngine.java
- javascript-modules-engine-java/src/main/java/org/jahia/modules/javascript/modules/engine/registrars/ViewsRegistrar.java
- javascript-modules-engine-java/src/main/java/org/jahia/modules/javascript/modules/engine/views/JSView.java
Remove usage of template package registry at the time views are registered to prevent race condition issue between the module registered and the template package available.
> BACKLOG-23522: bundle registration improvements

- javascript-modules-engine/tests/package.json
- javascript-modules-engine/tests/yarn.lock
https://jira.jahia.org/browse/QABACKLOG-1661
> QABACKLOG-1661: Updated to the latest version of jahia/cypress

- README.md
Remove links to img.shields.io.
> docs: Remove Shields images in README

- README.md
- javascript-modules-engine/package.json
- javascript-modules-engine/src/javascript/react/init.js
- javascript-modules-engine/tests/cypress/e2e/ui/reactVersionTest.cy.ts
- javascript-modules-engine/tests/jahia-module/package.json
- javascript-modules-engine/tests/jahia-module/settings/definitions.cnd
- javascript-modules-engine/tests/jahia-module/src/react/server/views/index.js
- javascript-modules-engine/tests/jahia-module/src/react/server/views/testReactVersion/TestReactVersion.jsx
- javascript-modules-engine/tests/jahia-module/yarn.lock
- javascript-modules-engine/yarn.lock
- javascript-modules-library/package.json
- javascript-modules-library/yarn.lock
Upgrade the backend engine to React 19.0.0.
For compatibility reasons, _react-i18next_ is also upgraded (to 15.4.0).
The only noticeable change is the import of `ReactDOMServer` from `react-dom/server.edge` instead of `react-dom/server`. Without it, we encounter the following error:
```
Uncaught ReferenceError: MessageChannel is not defined
```
> chore!: Upgrade to React 19

- jahia-test-module/package.json
- javascript-modules-library/package.json
- yarn.lock
Bumped TypeScript to latest (5.7.3)
> chore: bumped typescript version

- jahia-test-module/src/hooks/usePageAncestors.js
- javascript-modules-engine/tests/package.json
- javascript-modules-engine/tests/yarn.lock
- javascript-modules-library/package.json
- javascript-modules-library/src/nav/server/navBuilder/navBuilder.ts
- yarn.lock
This is not necessary if we don't use fragments or other graphql features that require injecting graphql through an AST
> refactor: removed unused graphql parsing-stringifying flow

- jahia-test-module/src/client/components/SampleHydrateInBrowserReact.jsx
- jahia-test-module/src/react/server/views/testReactClientSide/TestReactClientSide.jsx
- javascript-modules-engine/package.json
- javascript-modules-engine/rollup.config.mjs
- javascript-modules-engine/src/client-javascript/i18next/index.ts
- javascript-modules-engine/src/client-javascript/react/index.tsx
- javascript-modules-engine/tests/cypress/e2e/ui/reactClientSideTest.cy.ts
- javascript-modules-library/package.json
- javascript-modules-library/src/core/server/components/render/HydrateInBrowser.tsx
- javascript-modules-library/src/core/server/components/render/RenderInBrowser.tsx
- javascript-modules-library/src/core/server/components/render/internal/InBrowser.tsx
- yarn.lock
Use devalue (https://www.npmjs.com/package/devalue) instead of JSON to stringify JS objects:
- Allows more objects to be transmitted (Set, Map, Date...)
- Prevents accidental XSS: https://www.npmjs.com/package/devalue#xss-mitigation
> fix: use devalue.stringify instead of JSON.stringify

- .github/workflows/on-code-change.yml
- .github/workflows/on-merge.yml
- .github/workflows/schedule-sonar.yml
chore: rename npm module to javascript module (github workflows)
...
> chore: rename npm module to javascript module (github workflows)

- .github/workflows/skip-for-docs.yml
- CODEOWNERS
Doc-only CI to allow merging documentation changes instantly, without running tests
> ci: special documentation ci

- javascript-create-module/package.json
- yarn.lock
Rename _@jahia/javascript-create-module_ back to _@jahia/create-module_ following https://github.com/Jahia/javascript-modules/pull/116, to keep versions' history of the https://www.npmjs.com/package/@jahia/create-module package.
Then, https://www.npmjs.com/package/@jahia/javascript-create-module should be deleted (or redirected to https://www.npmjs.com/package/@jahia/create-module).
> build(create-module): Rename package to @jahia/create-module

- jahia-test-module/src/client/components/SampleHydrateInBrowserReact.jsx
- jahia-test-module/src/react/server/views/testReactClientSide/TestReactClientSide.jsx
- javascript-modules-engine/src/client-javascript/react/index.tsx
- javascript-modules-engine/tests/cypress/e2e/ui/reactClientSideTest.cy.ts
- javascript-modules-library/src/core/server/components/render/HydrateInBrowser.tsx
- javascript-modules-library/src/core/server/components/render/RenderInBrowser.tsx
- javascript-modules-library/src/core/server/components/render/internal/InBrowser.tsx
> feat: support interleaved ssr/csr/hydrated content

- README.md
> docs: update root readme

- docs/1-getting-started/5-view-content-in-full-page/README.md
> docs: 'authors' is possibly undefined

- docs/1-getting-started/4-making-a-blog/README.md
> docs: Remove unnecessary space on blog post

- docs/1-getting-started/1-dev-environment/README.md
- docs/1-getting-started/2-making-a-hero-section/README.md
- docs/1-getting-started/3-the-about-us-page/README.md
- docs/1-getting-started/4-making-a-blog/README.md
- docs/README.md
Small documentation update to hide empty pages and make it more accurate
> [!TIP]
> docs: hide unavailable pages

- pom.xml
Align the commit message added by the Maven Release Plugin when preparing the next version, with the [Conventional Commits specifications](https://www.conventionalcommits.org/en/v1.0.0/).
> [!TIP]
> chore: Update release preparation commit msg

- javascript-modules-engine/pom.xml
- javascript-modules-engine/rollup.config.mjs
Produce minified JS files for the browser.
Measured change for the Hello World:
Before: <img width="352" alt="image" src="https://github.com/user-attachments/assets/ce33550c-f85c-45b5-aed0-8eaf3a92c32c" />
After: <img width="375" alt="image" src="https://github.com/user-attachments/assets/9db9f675-6ba7-4b1c-aa94-b05943d1cf18" /> (-66%)
Note: the compatibility issues mentioned in the removed comment are pre-vite build, it was addressed by properly moving all JSM projects to the new jsx runtime
Closes #82 
> [!TIP]
> build: minify js client files

- javascript-modules-engine-java/src/main/java/org/jahia/modules/javascript/modules/engine/jsengine/GraalVMEngine.java
Closes https://github.com/Jahia/javascript-modules/issues/230.
Rely on [org.graalvm.home.Version](https://www.graalvm.org/sdk/javadoc/org/graalvm/home/Version.html) from GraalVM SDK to test wether a valid GraalVM is used to run Jahia or not.
From their documentation:
> A version utility to canonicalize and compare GraalVM versions. The GraalVM version string is not standardized and may change without notice. This class is designed to evolve with GraalVM to cover all used version formats in use. It allows to create, validate and compare GraalVM versions.
When using an invalid VM (for instance [Amazon Corretto 17](https://docs.aws.amazon.com/corretto/latest/corretto-17-ug/generic-linux-install.html)), the following warning will be added to the log:
```
WARN [GraalVMEngine] - Javascript …
```
> fix: GraalVM not correctly detected

- .github/workflows/on-release.yml
> ci: allow draft->prerelease workflow

- javascript-create-module/index.js
I'm old https://www.reddit.com/r/docker/comments/uzng7t/please_help_a_newbie_dockercompose_vs_docker/
> [!TIP]
> fix(create-module): it's docker compose now

- javascript-modules-library/src/components/render/RenderChild.tsx
- javascript-modules-library/src/components/render/RenderChildren.tsx
> feat: forward `RenderChild` props to `AddContentButtons`

- javascript-create-module/templates/module/dot/gitignore
Follow these recommendations: https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored
> [!TIP]
> fix: more precise gitignore

- javascript-modules-engine/src/javascript/react/init.tsx
Nothing specific, just a small code quality update
> [!TIP]
> style: small code quality update

- docs/3-reference/1-cnd-format/README.md
Following https://github.com/Jahia/jahia-private/issues/4066
> [!TIP]
> docs: update the definition of reference

- docs/3-reference/2-naming-conventions/README.md
New documentation page
> [!TIP]
> docs: naming conventions
