- javascript-modules-engine/tests/cypress/e2e/module/moduleSettingsTest.cy.ts
- javascript-modules-engine/tests/package.json
- javascript-modules-engine/tests/yarn.lock
https://jira.jahia.org/browse/TECH-1880
An HTML identifier has been renamed in https://github.com/Jahia/jcontent/pull/1367, more specifically [here](https://github.com/Jahia/jcontent/pull/1367/files#diff-46e6b939eae9f9b09395725ce1c3ca5fa751ed12da2d66c8be8cbfb1115e3d27R45) to use the name of the section instead of the display name, which broke a Cypress test.
Also, bump to version 3.35.0 for the @jahia/cypress dependency to include [this change](https://github.com/Jahia/jahia-cypress/pull/99).
> TECH-1880: Update HTML id used to select an element in a test

- javascript-modules-engine-java/pom.xml
https://jira.jahia.org/browse/SEC-122
Change the scope of the `java-ts-bind` dependency to `provided` to exclude the library from the Sonar analysis (done by the `-DskipProvidedScope=true` parameter in https://github.com/Jahia/jahia-modules-action/blob/main/sonar-analysis/action.yml#L116).
This should prevent SonarQube to list the security vulnerabilities related to the `java-ts-bind` dependency (see https://sonarqube.jahia.com/project/issues?resolved=false&types=VULNERABILITY&inNewCodePeriod=false&id=org.jahia.modules%3Ajavascript-modules).
> SEC-122: Mark java-ts-bind as a provided dependency

- .github/workflows/on-code-change.yml
- .github/workflows/on-merge.yml
- .github/workflows/on-release.yml
- javascript-modules-engine-java/.java-ts-bind/apply-patch.sh
- javascript-modules-engine-java/.java-ts-bind/package.json
- javascript-modules-engine-java/pom.xml
- javascript-modules-engine/pom.xml
- javascript-modules-engine/tests/jahia-module/package.json
- javascript-modules-engine/tests/jahia-module/yarn.lock
- javascript-modules-engine/yarn.lock
- javascript-modules-library/yarn.lock
- pom.xml
Add JDK17 as an OSGi requirement 
Update JS types to use JDK 17
> TECH-2011: add a jdk17 requirement for javascript-module-engine jahia module

- .github/workflows/schedule-sonar.yml
This aligns with the container used during build.
Run taking place here: https://github.com/Jahia/javascript-modules/actions/runs/12882590233
> fix: updated the version of the job_container

- pom.xml
https://jira.jahia.org/browse/TECH-2048
Bump the version of the plugin _org.sonatype.plugins:nexus-staging-maven-plugin_ to 1.7.0 (from 1.5.1), as the previous version is not compatible with JDK 17.
**NB:** https://github.com/Jahia/jahia-private/pull/2371 is not enough as _javascript-modules_ has its parent _org.jahia.modules:jahia-modules_ in version 8.2.0.0 (thus, without the bump of version).
> TECH-2048: Bump nexus-staging-maven-plugin to 1.7.0

- javascript-modules-engine/tests/jahia-module/yarn.lock
- javascript-modules-engine/yarn.lock
- javascript-modules-library/src/core/index.js
- javascript-modules-library/src/core/server/components/AddResources.jsx
- javascript-modules-library/src/core/server/components/index.js
- javascript-modules-library/src/core/server/components/render/index.js
- javascript-modules-library/src/core/server/components/render/internal/InBrowser.jsx
- javascript-modules-library/src/core/server/framework/index.js
- javascript-modules-library/src/core/server/hooks/index.js
- javascript-modules-library/src/core/server/hooks/useJCRQuery.js
- javascript-modules-library/src/core/server/hooks/useUrlBuilder.jsx
- javascript-modules-library/src/core/server/index.js
- javascript-modules-library/src/core/server/utils/index.js
- javascript-modules-library/src/core/server/utils/jcr/index.js
- javascript-modules-library/src/core/server/utils/urlBuilder/index.js
- javascript-modules-library/src/index.js
- javascript-modules-library/src/nav/index.js
- javascript-modules-library/src/nav/server/index.js
- javascript-modules-library/src/nav/server/navBuilder/index.js
Pure code quality change: removed all `export * from somewhere` statements. A file only containing this kind of statement is named a barrel file.
Rationale: it's not a good practice.[[1]](https://www.reddit.com/r/node/comments/1hailrd/are_barrel_files_always_a_good_practice_when/)[[2]](https://marvinh.dev/blog/speeding-up-javascript-ecosystem-part-7/) (it impacts performance and impairs tools) 
Instead, we have a single entry point for our library, with an explicit list of exports; we now fully control the exposed API.
> style: removed barrel files

- javascript-modules-engine/tests/jahia-module/yarn.lock
- javascript-modules-engine/yarn.lock
- javascript-modules-library/package.json
- javascript-modules-library/src/bin/jahia-deploy.mjs
- javascript-modules-library/tsconfig.json
- javascript-modules-library/yarn.lock
Copy the build scripts (to ~compile, clean, build, pack,~ deploy ~and watch~) from https://github.com/Jahia/javascript-components/ to this repository, so the project can get rid of the dependency towards `@jahia/scripts dependency`.
Example of cleanup in Luxe: https://github.com/Jahia/luxe-jahia-demo/pull/178
When the `@jahia/javascript-modules-library` dependency is added to a project, the following commands are exposed:
- ~`jahia-build` : simply calls the production build (`jahia-build_production`)~
-  ~`jahia-build_development`: builds the project with webpack using the _development_ mode~
- ~`jahia-build_production`: builds the project with webpack default mode (_production_)~
- ~`jahia-clean`: cleans the generated folder created by the build (`dist/`)~
- `jahia-deploy`: builds the …
> build: add scripts to the mono repository

- javascript-modules-engine/pom.xml
- javascript-modules-library/pom.xml
- pom.xml
Refactor the usage of the Maven plugin _com.github.eirslett:frontend-maven-plugin_ to centralize its configuration.
Bump versions:
- `yarn` to 1.22.22
- `node` to 22.10.0
- `npm` to 11.1.0
> build: refactor frontend plugin and bump node/yarn/npm versions

- javascript-modules-library/package.json
- yarn.lock
Remove the `typedoc` dependency that was re-added by mistake [here](https://github.com/Jahia/javascript-modules/commit/3a1a46421ba39ddb8e5dfb6496198918dd36c4e1#diff-6e6ade7b2bc5d4dc0c132d6782dab4a2cb1d62771ac87d3cc9ab349821d4aadcR45) (initially removed in https://github.com/Jahia/javascript-modules/pull/60).
> build: Remove typedoc dependency

- .gitignore
- jahia-test-module/src/react/server/views/testRender/TestRender.jsx
- javascript-modules-library/src/core/server/components/AddContentButtons.tsx
Fixes #64: `<AddContentButtons>` now takes a list of types as its nodeTypes property `<AddContentButtons nodeTypes={['jnt:text', 'jnt:bigText']}>`
The previous signature (space-separated list) is still working but marked as `@deprecated`:
> fix: AddContentButtons now takes a list of nodeTypes

- javascript-modules-engine/tests/cypress/e2e/module/moduleTransformationTest.cy.ts
Fix broken nightly tests (ex: https://github.com/Jahia/javascript-modules/actions/runs/13402693890/job/37436695791).
This test should be re-renabled once javascript-modules-engine 0.4.0 (or greater) is included in _jahia-pack_.
> fix: Remove test on Jahia-Depends

- javascript-modules-engine/package.json
- javascript-modules-engine/rollup.config.mjs
- javascript-modules-library/bin/jahia-deploy.mjs
- javascript-modules-library/package.json
- vite-plugin/package.json
- yarn.lock
Small maintenance PR: lint all npm packages when building to avoid broken releases
`@jahia/javascript-modules-library` no longer publishes real code to npm to avoid misuse. It means that we can no longer import `@jahia/javascript-modules-library` on our side neither and we need a custom resolver to do that. That's why there is a new inline rollup plugin that does just that: properly resolve `@jahia/javascript-modules-library`
> build: lint all npm packages with publint

- javascript-modules-engine/pom.xml
Declare _javascript-modules-library_ as a _pom_ dependency (as per the changes in https://github.com/Jahia/javascript-modules/pull/119) to fix the `mvn deploy`.
> build: javascript-modules-library is now a pom dependency

- .github/workflows/on-code-change.yml
- CODEOWNERS
Avoid wasting human and machine time for short iterations in the product team
> ci: skip all workflows for upcoming documentation

- javascript-create-module/pom.xml
- pom.xml
- vite-plugin/pom.xml
As the publication is done using a `yarn npm publish`, there is no need to install npm as part of the initialization phase.
This is similar to what is configured for the [_javascript-modules-libray_ module](https://github.com/Jahia/javascript-modules/blob/main/javascript-modules-library/pom.xml#L40).
> build: Remove installation of npm

- javascript-modules-engine/pom.xml
- pom.xml
When packing the javascript-modules-engine, generate a Software Bill of Materials (SBOM) containing the aggregate of all direct and transitive dependencies of the module.
> build(engine): Generate SBOM as part of the build

- vite-plugin/src/index.ts
> fix(vite-plugin): vite should bundle all dependencies in ssr mode

- javascript-modules-engine/package.json
- vite-plugin/package.json
- vite-plugin/src/index.ts
- vite-plugin/src/insert-filename.ts
- yarn.lock
Adds support for all `export default` expressions, when it was previously limited to `export default function`.
@baptistegrimaud Can you keep one `const Component = ...; export default Component` in #147 please?
> [!TIP]
> feat(plugin-vite): support all `export default` expressions

- jahia-test-module/src/react/server/views/testAbsoluteAreas/TestAbsoluteAreas.tsx
- jahia-test-module/src/react/server/views/testAreas/TestAreas.tsx
- jahia-test-module/src/react/server/views/testRender/TestRenderEditable.tsx
- javascript-modules-engine/tests/cypress/e2e/ui/absoluteAreaTest.cy.ts
- javascript-modules-library/src/core/server/components/AbsoluteArea.tsx
- javascript-modules-library/src/core/server/components/Area.tsx
- javascript-modules-library/src/core/server/components/render/Render.tsx
Breaking change!
All attributes now default to false: instead of writing `<Area editable={false}>` you'd write `<Area readOnly>`
Closes #180 
> [!TIP]
> feat(library)!: made attributes default to false

- javascript-create-module/template/vite.config.mjs
- vite-plugin/package.json
This is required to work on Windows with FNM (yarn is not a binary but a .ps1 script) 
> [!TIP]
> fix(template): support windows

- javascript-modules-engine/tests/package.json
- javascript-modules-engine/tests/yarn.lock
Update to the latest release of _@jahia/jcontent-cypress_ to include https://github.com/Jahia/jcontent/pull/1681/files and fix the automated tests using `JContent`.
> chore(deps): Update @jahia/jcontent-cypress to 3.3.0-tests.1

- jahia-test-module/src/react/server/views/testAbsoluteAreas/TestAbsoluteAreas.tsx
- jahia-test-module/src/react/server/views/testAreaColumns/TestAreaColumns.tsx
- jahia-test-module/src/react/server/views/testAreas/TestAreas.tsx
- javascript-modules-engine-java/.java-ts-bind/package.json
- javascript-modules-engine-java/pom.xml
- javascript-modules-engine-java/src/main/java/org/jahia/modules/javascript/modules/engine/js/server/RenderHelper.java
- javascript-modules-engine-java/src/test/java/org/jahia/modules/javascript/modules/engine/js/server/RenderHelperTest.java
- javascript-modules-engine/tests/cypress.config.ts
- javascript-modules-engine/tests/cypress/e2e/ui/absoluteAreaTest.cy.ts
- javascript-modules-engine/tests/cypress/e2e/ui/areaTest.cy.ts
- javascript-modules-library/README.md
- javascript-modules-library/src/core/server/components/AbsoluteArea.tsx
- javascript-modules-library/src/core/server/components/Area.tsx
Addresses https://github.com/Jahia/javascript-modules/issues/179.
Refactor and simplify `<Area>` and `<AbsoluteArea>` components (with **breaking changes**!).
To use a fixed JCR node content of a given page:
```
<AbsoluteArea name="yourContentNode" parent={yourPageNode}>
```
This would store (and create if it does not exist) the content node `yourContentNode` (of type `"jnt:contentList"`) as a child node of `yourPageNode` (a `JCRNodeWrapper`).
For instance, to use the `main` node of the home page:
```
<AbsoluteArea name="main" parent={renderContext.getSite().getHome()} />
```
Or to use a different page (at a custom hierarchy):
```
<AbsoluteArea name="main" parent={renderContext.getSite().getNode("your-page/your-sub-page")} />
```
A content node relative to the current page can also be …
> feat!: Refactor <Area> and <ContentArea> components

- docs/1-getting-started/1-dev-environment/README.md
- javascript-create-module/README.md
- javascript-create-module/index.js
Addresses https://github.com/Jahia/javascript-modules/issues/242.
Specify to use `@latest` when running the `npm init` command to ensure the latest version is used, in case the package already exists globally.
As per the [npm-init documentation](https://docs.npmjs.com/cli/v8/commands/npm-init):
> Note: if a user already has the create-<initializer> package globally installed, that will be what npm init uses. If you want npm to use the latest version, or another specific version you must specify it
> [!TIP]
> docs: Use latest version for init module

- .github/workflows/manual-run.yml
- .github/workflows/nightly.yml
- samples/README.md
Fix the URLs used in provisioning files to import the prepackaged site (the version must be specified - `LATEST` simply takes the latest available on Nexus).
This should fix the [nightly tests](https://github.com/Jahia/javascript-modules/actions/runs/14232158874).
> [!TIP]
> fix: Fix URLs to import the prepackaged site

- jahia-test-module/pom.xml
- javascript-create-module/package.json
- javascript-create-module/pom.xml
- javascript-modules-engine-java/pom.xml
- javascript-modules-engine-java/src/main/java/org/jahia/modules/javascript/modules/engine/jshandler/JavascriptProtocolConnection.java
- javascript-modules-engine/pom.xml
- javascript-modules-engine/tests/provisioning-manifest-snapshot.yml
- javascript-modules-library/package.json
- javascript-modules-library/pom.xml
- pom.xml
- samples/hydrogen-prepackaged/pom.xml
- samples/hydrogen/package.json
- samples/hydrogen/pom.xml
- vite-plugin/package.json
- vite-plugin/pom.xml
During testing, we discovered that javascript-modules-engine was not compatible with Jahia 8.2.0.0 anymore, it was decided to update the parent to 8.2.1.0.
Updated all versions back to 0.6.1-SN
> fix: updated jahia parent to 8.2.1.0 and rolled back codebase version to 0.6.1

- samples/hydrogen/pom.xml
Attach Hydrogen (sample JS module) artifact (generated in `dist/package.tgz`) to the Maven lifecycle, so the `tgz` archive gets installed/deployed during the Maven build.
This should fix the issue encountered with the nighlty tests where the package can't be retrieved:
```
ERROR [InstallBundle] - Cannot install js:mvn:org.jahia.samples/javascript-modules-samples-hydrogen/0.6.1-SNAPSHOT/tgz = java.io.IOException. Please make sure the artifact is reachable within the registered maven repositories (network, credentials ...)
```
> [!TIP]
> build(samples): Attach Hydrogen artifact to the Maven build

- javascript-modules-engine/tests/provisioning-manifest-snapshot.yml
Following the [release of 0.6.1](https://github.com/Jahia/javascript-modules/releases/tag/0_6_1), the provisioning files (to install the test modules) must be aligned with the current development version (0.7.0-SNAPSHOT)
> [!TIP]
> build: Align versions in provisioning with release 0.7.0-SNAPSHOT

- javascript-create-module/pom.xml
- javascript-modules-library/pom.xml
- pom.xml
- vite-plugin/pom.xml
When executing a `mvn deploy` (done by the  _On merge to main_ Github workflow), deploy an _alpha_ version to the [NPM registry](https://www.npmjs.com/), similar to what is done with Maven snapshots.
**Important**: As a `tag` parameter is passed to the [`yarn npm publish`](https://yarnpkg.com/cli/npm/publish) command, the default _latest_ tag is overwritten, meaning the alpha version getting published will *not* be resolved by `"@jahia/javascript-modules-library": "latest"`.
The following modules have their NPM packages published:
- [@jahia/create-module](https://www.npmjs.com/package/@jahia/create-module)
- [@jahia/javascript-modules-library](https://www.npmjs.com/package/@jahia/javascript-modules-library)
- [@jahia/vite-plugin](https://www.npmjs.com/package/@jahia/vite-plugin)
The …
> build: Use an 'alpha' tag when building on merge to main

- .github/workflows/on-merge.yml
Following https://github.com/Jahia/javascript-modules/pull/254, the authentication token to allow publication to https://registry.npmjs.org has to be set in the Github workflow when merging to main.
Should fix [the error](https://github.com/Jahia/javascript-modules/actions/runs/14327789688/job/40161491037) encountered during the publication step:
```
[INFO] Running 'yarn npm publish --tag alpha --access public' in /__w/javascript-modules/javascript-modules/vite-plugin
[INFO] ➤ YN0000: README.md
[INFO] ➤ YN0000: dist/index.d.ts
[INFO] ➤ YN0000: dist/index.js
[INFO] ➤ YN0000: package.json
[INFO] ➤ YN0033: No authentication configured for request
[INFO] ➤ YN0000: Failed with errors in 0s 24ms
...
Error:  Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.15.1:yarn …
```
> ci: configure credentials to publish npm package

- jahia-test-module/src/react/server/views/testReactVersion/TestReactVersion.tsx
- javascript-modules-engine/tests/cypress/e2e/ui/reactVersionTest.cy.ts
- vite-plugin/src/index.ts
Closes #258
Replace NODE_ENV on build using https://vite.dev/config/shared-options.html#define
> [!TIP]
> feat(vite-plugin): replace process.env.NODE_ENV

- pom.xml
Remove the duplicated declaration of `build-helper-maven-plugin` (already declared [here](https://github.com/Jahia/javascript-modules/blob/main/pom.xml#L142)) that currently generates a warning when building:
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jahia.test:javascript-modules-engine-test-module:pom:0.7.0-SNAPSHOT
[WARNING] 'build.pluginManagement.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.codehaus.mojo:build-helper-maven-plugin @ org.jahia.modules:javascript-modules:0.7.0-SNAPSHOT, /Users/baptistegrimaud/Documents/code/jahia/javascript-modules/pom.xml, line 157, column 25
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for …
```
> chore: Remove duplicated plugin declaration

- javascript-modules-engine-java/.java-ts-bind/package.json
- javascript-modules-engine-java/pom.xml
- javascript-modules-engine-java/src/main/java/org/jahia/modules/javascript/modules/engine/js/server/RenderHelper.java
- javascript-modules-engine-java/src/main/java/org/jahia/modules/javascript/modules/engine/jsengine/GraalVMEngine.java
- javascript-modules-engine-java/src/main/java/org/jahia/modules/javascript/modules/engine/jshandler/JavascriptProtocolConnection.java
- javascript-modules-engine-java/src/main/java/org/jahia/modules/javascript/modules/engine/views/JavascriptTemplatesNodeChoiceListInitializer.java
Use a single Apache Commons Lang (`commons-lang3`) library instead of 2 (`commons-lang` and `commons-lang3`).
Consequently, this removes the `org.apache.commons.lang` from the list of dependencies in the `Import-Package`.
> [!TIP]
> build: Migrate commons-lang -> commons-lang3

- javascript-modules-engine-java/.java-ts-bind/package.json
- javascript-modules-engine-java/pom.xml
Remove Spring dependencies from the generation of the TypeScript Declaration files (`*.d.ts`).
> [!TIP]
> build: Remove Spring from *.d.ts files

- jahia-test-module/pom.xml
- javascript-create-module/pom.xml
- javascript-modules-engine-java/.java-ts-bind/package.json
- javascript-modules-engine-java/pom.xml
- javascript-modules-engine/pom.xml
- javascript-modules-library/pom.xml
- pom.xml
- samples/hydrogen/pom.xml
- vite-plugin/pom.xml
Cleanup Maven POM files and explicitly declare the dependencies.
- the build ensures all the dependencies used are declared in the `pom.xml`, and that all declared dependencies are used
- `ops4j-base-lang-1.5.0.jar` is no longer embedded in the bundle, as the package `org.ops4j.lang` is already exported by Jahia
> [!TIP]
> build: cleanup Maven dependencies

- javascript-modules-engine/pom.xml
Remove the imports of [graphql-dxm-provider's APIs](https://github.com/Jahia/graphql-core/tree/master/graphql-dxm-provider) as they are not used by the _JavaScript Modules Engine_.
Follows https://github.com/Jahia/javascript-modules/pull/287.
> [!TIP]
> build: Remove GraphQL OSGI imports

- pom.xml
Follows https://github.com/Jahia/java-ts-bind/pull/18 to use java-ts-bind with a fix for [CVE-2023-2976](https://nvd.nist.gov/vuln/detail/cve-2023-2976).
This fixes the [Sonar analysis workflow](https://github.com/Jahia/javascript-modules/actions/runs/14828780031).
> [!TIP]
> build(sec): Fix CVE-2023-2976 (Google Guava)

- .github/workflows/on-merge.yml
Should fix the error:
```
[INFO] ➤ YN0035: Failed to save packument. A common cause is if you try to publish a new package before the previous package has been fully processed.
[INFO] ➤ YN0035:   Response Code: 409 (Conflict)
[INFO] ➤ YN0035:   Request Method: PUT
[INFO] ➤ YN0035:   Request URL: https://registry.yarnpkg.com/@jahia%2fjavascript-modules-library
[INFO] ➤ YN0000: Failed with errors in 1s 613ms
```
encountered when multiple "on merge" workflows are executed in parallel ([example here](https://github.com/Jahia/javascript-modules/actions/runs/14833988262/job/41642616520))
> [!TIP]
> build: Disable concurrency for 'on merge' workflow

- javascript-modules-engine/rollup.config.mjs
- javascript-modules-library/src/components/render/internal/InBrowser.tsx
- javascript-modules-library/src/globals.d.ts
Closes #346 
Changelog entry:
``- We improved hydration performance by inserting `<link rel="modulepreload">` hints referencing all the JS files used. The performance gain should be noticed on weak connections and performance tests. (#349)``
> feat: insert <link rel="modulepreload"> to improve hydration perf

- javascript-modules-library/src/framework/jahiaComponent.tsx
Removed unnecessary indirection: JCR properties can resolve nodes directly
> [!TIP]
---
Testing covered by automated tests
> refactor: use native jcr node resolution

- javascript-create-module/package.json
In https://github.com/Jahia/javascript-modules/pull/407, the `template/` folder and its content got moved to `templates/` but the `package.json` did not get updated accordingly.
Leading to an incomplete package:
> [!TIP]
> fix: templates/ not packaged in create-module

- javascript-modules-engine-java/src/main/java/org/jahia/modules/javascript/modules/engine/js/server/GQLHelper.java
- javascript-modules-engine/tests/cypress/e2e/ui/gqlTest.cy.ts
Use the request encoding (or `UTF-8` as default) for grqphQL queries from the `useGQLQuery` component. 
A Cypress test have been updated to ensure encoding is done properly. 
> [!TIP]
> fix: use same encoding as request for GQL queries

- javascript-modules-engine/src/javascript/react/init.tsx
- javascript-modules-engine/tests/cypress/e2e/ui/renderTest.cy.ts
- javascript-modules-library/src/components/AbsoluteArea.tsx
- javascript-modules-library/src/components/AddContentButtons.tsx
- javascript-modules-library/src/components/AddResources.tsx
- javascript-modules-library/src/components/Area.tsx
- javascript-modules-library/src/components/render/Render.tsx
Use a custom element (prefixed with `jsm-`) to avoid potential conflicts and type errors.
Peer PR: https://github.com/Jahia/luxe-jahia-demo/pull/270
> [!TIP]
> refactor: use a custom element for raw html wrapping

- docs/2-guides/2-island-architecture/README.md
> docs: fix images

- docs/1-getting-started/0-introduction/README.md
- docs/1-getting-started/1-dev-environment/README.md
- docs/1-getting-started/2-making-a-hero-section/README.md
- docs/1-getting-started/3-the-about-us-page/README.md
- docs/1-getting-started/4-making-a-blog/README.md
- docs/1-getting-started/5-view-content-in-full-page/README.md
- docs/1-getting-started/6-building-a-nav-bar/README.md
- docs/2-guides/1-building-a-feedback-form/README.md
- docs/2-guides/2-island-architecture/README.md
- docs/README.md
> docs: fix typo in jcr path name

- docs/1-getting-started/2-making-a-hero-section/README.md
- docs/1-getting-started/3-the-about-us-page/README.md
- docs/1-getting-started/5-view-content-in-full-page/README.md
> docs: fix some more typos

- vite-plugin/src/build-success.ts
- vite-plugin/src/build-successful.ts
- vite-plugin/src/index.ts
Closes #490 
Now we try to run the callback at the end of each build. If another build is in progress, running the callback is skipped.
> [!TIP]
> fix(vite-plugin): ensure all builds succeed before callback

- javascript-modules-engine/src/client/hydrate.tsx
Reported by @hduchesne: the error message always mentions hydration, but that's not always hydration under the hood
> [!TIP]
> fix(engine): generic hydration error message

- javascript-modules-engine-java/src/main/java/org/jahia/modules/javascript/modules/engine/jsengine/JSFileSystem.java
Testing on Windows failed at a different yet unexpected step, see #500
Fix confirmed to be working by @x0h01 🎉
> [!TIP]
> fix: ensure internal graal imports are ignored on windows

- javascript-modules-engine/tests/provisioning-manifest-snapshot.yml
Simplify provisioning files by replacing hard-coded versions by the Maven "metaversion" `LATEST`, that points to the latest version (including releases and snapshots).
The main benefit is that we won't need to update those files anymore when releasing (that bumps the version).
Run to validate the change: https://github.com/Jahia/javascript-modules/actions/runs/18312013907
> [!TIP]
> ci: simplify provisioning files by removing hard-coded versions

- javascript-create-module/package.json
`yarn create @jahia/module` should work the same as `npm init @jahia/module@latest` but fails because of filesystem errors. [This flag](https://yarnpkg.com/configuration/manifest#preferUnplugged) enforces a physical filesystem (node_modules) instead of a virtual one (zipfs).
> [!TIP]
> fix(create-module): ensure compatibility with yarn create
